echo "File sharing Overview"
echo "One simple file sharing tool is command: scp (Secure Copy)"
echo "It works exatly same as cp command"
echo "It allows you to copy some file to another pc in SAME NETWORK"
echo "Works via SSH"
echo "So all your actions are using the same authentication and security as ssh."
echo "To copy a file from a local host to a remote host:"
echo "scp myfile.txt username@remotehostIpOrDomainName(?.com/.org):/remote/directory"
echo "To copy a file from a remote host to your local host"
echo "scp username@remotehost.com:/remote/directory/myfile.txt /local/directory"
echo "To copy a directory from your local host to a remote host"
echo "scp -r mydir username@remotehost.com:/remote/directory"
echo "You can do vice versa to copy a directory from remote host to localhost"
echo
